# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20d22bb5f9529e60573a9171d667e073f5f13899a216793f0fe8e637b56a0d8e6f17030a89a133936426cee28d59a86c839df8f1a8b3765af92d0346b10baa18

test:
  secret_key_base: 620729be9f86170637283b4ea2bf1172b50bc7a29b01024dab885d4d2d875f9d04b964d7378a387d31766bb277657cad7cd777074ebf4a7c96975f918a1dc3e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
